import { Link, useParams } from "react-router-dom";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CtaBand, MarketingLayout, PageHero } from "@/components/marketing/MarketingLayout";
import { industries, referenceImages } from "@/data/referenceMarketing";

export default function Industries() {
  const { industryId } = useParams();
  const industry = industries.find((item) => item.id === industryId);
  return <MarketingLayout>{industry ? <>
    <section className="border-b border-intro-foreground/10 px-5 pb-16 pt-20 sm:px-8 sm:pt-24">
      <div className="mx-auto grid max-w-[1200px] gap-12 lg:grid-cols-2 lg:items-center">
        <div className="marketing-enter"><Link to="/industries" className="inline-flex items-center gap-2 text-sm text-intro-muted hover:text-intro-foreground"><ArrowLeft size={16}/> All industries</Link><p className="mt-8 text-xs font-bold uppercase text-intro-accent">{industry.name}</p><h1 className="mt-4 max-w-xl font-display text-5xl leading-tight sm:text-6xl">{industry.headline}</h1><p className="mt-5 max-w-xl leading-7 text-intro-muted">{industry.description}</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild className="bg-intro-primary text-intro-foreground"><Link to="/contact">Get in touch <ArrowRight size={16}/></Link></Button><Button asChild variant="outline" className="border-intro-foreground/20 bg-transparent text-intro-foreground"><Link to="/platform">See the platform</Link></Button></div></div>
        <div className="marketing-enter marketing-delay rounded-lg border border-intro-foreground/10 bg-intro-surface p-6"><p className="mb-5 text-xs font-semibold uppercase text-intro-muted">{industry.name} · overview</p>{industry.stats.map(([label,value]) => <div key={label} className="flex justify-between gap-4 border-t border-intro-foreground/10 py-4 text-sm"><span className="text-intro-muted">{label}</span><strong className="text-intro-highlight">{value}</strong></div>)}</div>
      </div>
    </section>
    <section className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-[1200px]"><p className="text-xs font-bold uppercase text-intro-accent">{industry.flowLabel}</p><h2 className="mt-3 font-display text-4xl">{industry.flowTitle}</h2><div className="mt-9 grid gap-4 md:grid-cols-3">{industry.flow.map(item=><article key={item.title} className="rounded-lg border border-intro-foreground/10 bg-intro-surface p-7"><p className="text-xs font-bold uppercase text-intro-accent">{item.label}</p><h3 className="mt-3 text-lg font-semibold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-intro-muted">{item.copy}</p></article>)}</div></div></section>
    {industry.feature && <section className="border-y border-intro-foreground/10 bg-intro-surface px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-[1200px] gap-12 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase text-intro-accent">{industry.feature.eyebrow}</p><h2 className="mt-3 font-display text-4xl">{industry.feature.title}</h2><p className="mt-4 leading-7 text-intro-muted">{industry.feature.copy}</p>{industry.feature.items.map(item=><div key={item.title} className="mt-5 flex gap-3 border-t border-intro-foreground/10 pt-5"><Check className="mt-1 h-5 w-5 shrink-0 text-intro-success"/><div><h3 className="font-semibold">{item.title}</h3><p className="mt-1 text-sm text-intro-muted">{item.copy}</p></div></div>)}</div><div className="self-center rounded-lg border border-intro-foreground/10 bg-intro p-7"><p className="mb-5 text-xs font-semibold uppercase text-intro-muted">Workspace preview</p>{industry.feature.rows.map(([label,value])=><div key={label} className="flex justify-between gap-3 border-t border-intro-foreground/10 py-4 text-sm"><span>{label}</span><span className="text-intro-accent">{value}</span></div>)}</div></div></section>}
    <section className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-[1200px]"><h2 className="font-display text-4xl">Why {industry.name.toLowerCase()} teams switch to Lexora</h2><div className="mt-9 grid gap-4 md:grid-cols-3">{industry.why.map((item,i)=><article key={item.title} className="border-t border-intro-foreground/20 pt-6"><span className="font-display text-3xl text-intro-accent">0{i+1}</span><h3 className="mt-4 font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-intro-muted">{item.copy}</p></article>)}</div></div></section><CtaBand title={industry.cta} copy="Talk to our team about your organisation."/>
  </> : <>
    <PageHero eyebrow="Industries" title="Purpose-built for how your sector operates" subtitle="Every industry has different regulatory pressures, workflows, and reporting obligations. Lexora adapts to each one."/>
    <section className="bg-intro-soft px-5 py-12 text-intro-soft-foreground sm:px-8"><div className="mx-auto max-w-[1200px]"><div className="grid grid-cols-2 gap-2 overflow-hidden rounded-lg sm:grid-cols-4">{referenceImages.strip.map((src,i)=><div key={i} className="relative aspect-[4/3] overflow-hidden"><img src={src} alt={["Engineering","Manufacturing","Natural resources","Real estate"][i]} className="h-full w-full object-cover transition-transform duration-700 hover:scale-105"/><span className="absolute bottom-3 left-3 text-xs font-semibold text-intro-foreground drop-shadow-md">{["Engineering","Manufacturing","Natural resources","Real estate"][i]}</span></div>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{industries.map(item=><Link key={item.id} to={`/industries/${item.id}`} className="group overflow-hidden rounded-lg border border-intro-soft-border bg-intro-soft-raised transition-transform duration-300 hover:-translate-y-1"><div className="aspect-[2/1] overflow-hidden"><img src={item.image} alt="" loading="lazy" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"/></div><div className="p-5"><h2 className="text-lg font-semibold">{item.name}</h2><p className="mt-2 text-sm leading-6 text-intro-soft-muted">{item.summary}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-intro-primary">Explore <ArrowRight size={14}/></span></div></Link>)}</div></div></section>
  </>}</MarketingLayout>;
}
